spring.application.name=backend
spring.datasource.url=jdbc:mysql://localhost:3306/watches_db
spring.datasource.username=root
spring.datasource.password=0000
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.address=0.0.0.0
server.tomcat.max-part-count=1000

# files properties
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=11MB
spring.servlet.multipart.max-request-size=20MB

# Optional: Specify the MySQL driver explicitly
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA Hibernate dialect (optional but recommended)
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# JWT properties
security.jwt.secret-key=ey3as7bar9aah15ama1d21noura22ab1ukh/ali!ls]ar0aman[ass=r2aaw2a8ysa
# 1 year
security.jwt.expiration-time=31536000000